import { useState, type FormEvent } from 'react'
import { ArrowLeft, ArrowRight, CheckCircle2, Eye, EyeOff, Loader2 } from 'lucide-react'
import { Link, Navigate, useNavigate, useParams } from 'react-router-dom'
import { Logo } from '../components/Logo'
import { useAuth } from '../context/AuthContext'
import { supabase } from '../lib/supabase'
type View = 'login'|'signup'|'forgot'|'reset'
const callbackUrl = () => `${window.location.origin}/auth/callback`
export function AuthPage(){
 const { mode }=useParams(); const view=(['login','signup','forgot','reset'].includes(mode||'')?mode:'login') as View; const navigate=useNavigate(); const {session,configured}=useAuth(); const [busy,setBusy]=useState(false);const [show,setShow]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('')
 if(session) return <Navigate to="/dashboard" replace/>;
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setError('');setMessage('');if(!supabase||!configured){setError('Supabase is not configured. Create .env.local from .env.example, then restart Vite.');return}const form=new FormData(e.currentTarget);const email=String(form.get('email')||'');const password=String(form.get('password')||'');setBusy(true);try{if(view==='login'){const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;navigate('/dashboard')}else if(view==='signup'){if(password!==String(form.get('confirm')))throw new Error('Passwords do not match.');const {data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:String(form.get('name'))},emailRedirectTo:callbackUrl()}});if(error)throw error;if(data.session)navigate('/dashboard');else setMessage('Check your inbox to confirm your email, then return to sign in.')}else if(view==='reset'){if(password!==String(form.get('confirm')))throw new Error('Passwords do not match.');const {error}=await supabase.auth.updateUser({password});if(error)throw error;setMessage('Password updated. You can now sign in.')}else{const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/reset`});if(error)throw error;setMessage('Reset link sent. Check your inbox.')}}catch(cause){setError(cause instanceof Error?cause.message:'Authentication could not be completed.')}finally{setBusy(false)}}
 const google=async()=>{setError('');if(!supabase||!configured){setError('Supabase is not configured. Create .env.local from .env.example, then restart Vite.');return}setBusy(true);const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:callbackUrl()}});if(error){setError(error.message);setBusy(false)}}
 const content={login:{eyebrow:'Welcome back',title:'Your spending has been waiting.',sub:'Sign in to pick up where your clarity left off.'},signup:{eyebrow:'Start your reset',title:'Know where your money goes.',sub:'A few minutes now. A calmer year ahead.'},forgot:{eyebrow:'No worries',title:'Let us get you back in.',sub:'Enter your email and we will send a reset link.'},reset:{eyebrow:'New beginning',title:'Choose a fresh password.',sub:'Make it strong, then get back to saving.'}}[view]
 const action=view==='forgot'?'Send reset link':view==='signup'?'Create my free account':view==='reset'?'Update password':'Sign in'
 return <div className="auth-shell"><div className="auth-aurora one"/><div className="auth-aurora two"/><header><Logo/><Link to="/" className="back"><ArrowLeft size={16}/> Back to home</Link></header><aside><div className="auth-quote"><span>“</span><p>Small, intentional choices turn money stress into room to breathe.</p><div><i/> <b>Offtrack principle #01</b></div></div></aside><section className="auth-card"><div className="auth-head"><p>{content.eyebrow}</p><h1>{content.title}</h1><span>{content.sub}</span></div>{message&&<div className="notice success"><CheckCircle2 size={17}/>{message}</div>}{error&&<div className="notice error">{error}</div>}<form onSubmit={submit}>{view==='signup'&&<label>Full name<input name="name" required placeholder="Jane Smith" autoComplete="name"/></label>}{view!=='reset'&&<label>Email address<input name="email" type="email" required placeholder="you@example.com" autoComplete="email"/></label>}{view!=='forgot'&&<label>{view==='reset'?'New password':'Password'}<div className="password"><input name="password" type={show?'text':'password'} required minLength={6} placeholder="••••••••" autoComplete={view==='signup'||view==='reset'?'new-password':'current-password'}/><button type="button" onClick={()=>setShow(!show)} aria-label="Toggle password visibility">{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>}{(view==='signup'||view==='reset')&&<label>Confirm password<input name="confirm" type="password" required minLength={6} placeholder="••••••••" autoComplete="new-password"/></label>}{view==='login'&&<div className="form-row"><label className="check"><input type="checkbox" name="remember" defaultChecked/> <span>Remember me</span></label><Link to="/forgot">Forgot password?</Link></div>}<button disabled={busy} className="button submit">{busy?<Loader2 className="spin" size={17}/>:action}{!busy&&<ArrowRight size={16}/>}</button></form>{view!=='forgot'&&view!=='reset'&&<><div className="divider"><span>or continue with</span></div><button onClick={google} disabled={busy} className="google"><b>G</b> Continue with Google</button></>}<div className="switch">{view==='login'?<>New to Offtrack? <Link to="/signup">Create an account</Link></>:view==='signup'?<>Already have an account? <Link to="/login">Sign in</Link></>:<Link to="/login">Return to sign in</Link>}</div></section></div>
}
