import { useEffect, useMemo, useState, type ReactNode } from 'react'
import { Bell, CalendarClock, ChevronRight, CircleDollarSign, MoreHorizontal, Search, Sparkles, TrendingDown, WalletCards, X } from 'lucide-react'
import FullCalendar from '@fullcalendar/react'
import dayGridPlugin from '@fullcalendar/daygrid'
import { BarChart, Bar, Cell, PieChart, Pie, ResponsiveContainer, Tooltip, XAxis } from 'recharts'
import { AppSidebar } from '../components/AppSidebar'
import { SubscriptionModal } from '../components/SubscriptionModal'
import { CancelAssistant } from '../components/CancelAssistant'
import { deleteSubscription, getSubscriptions, saveSubscription } from '../lib/subscriptions'
import { useAuth } from '../context/AuthContext'
import { supabase } from '../lib/supabase'
import type { Subscription } from '../types'
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n)
const monthly=(s:Subscription)=>s.billing_cycle==='yearly'?s.cost/12:s.cost
export function Dashboard(){const {session,signOut}=useAuth();const [active,setActive]=useState('overview');const [items,setItems]=useState<Subscription[]>([]);const [loading,setLoading]=useState(true);const [modal,setModal]=useState<Subscription|undefined>();const [newModal,setNewModal]=useState(false);const [query,setQuery]=useState('');const userId=session?.user.id||'demo';useEffect(()=>{getSubscriptions(userId).then(setItems).catch(console.error).finally(()=>setLoading(false))},[userId]);const total=useMemo(()=>items.filter(x=>x.status!=='cancelled').reduce((a,x)=>a+monthly(x),0),[items]);const save=async(value:Partial<Subscription>)=>{const saved=await saveSubscription({...value,id:modal?.id,user_id:userId});setItems(old=>modal?old.map(x=>x.id===modal.id?saved:x):[saved,...old]);setModal(undefined);setNewModal(false)};const firstName=session?.user.user_metadata.full_name?.split(' ')[0]||'Priya';let view:ReactNode=active==='overview'?<Overview total={total} items={items} onSee={()=>setActive('subscriptions')}/>:active==='subscriptions'?<Subscriptions items={items.filter(x=>x.name.toLowerCase().includes(query.toLowerCase()))} query={query} setQuery={setQuery} onEdit={setModal} onDelete={async id=>{await deleteSubscription(id);setItems(x=>x.filter(s=>s.id!==id))}}/>:active==='calendar'?<Calendar items={items}/>:active==='assistant'?<CancelAssistant items={items}/>:active==='analytics'?<Analytics items={items}/>:<EmptyPanel active={active}/>;return <div className="app-shell"><AppSidebar active={active} setActive={setActive} onAdd={()=>setNewModal(true)} onSignOut={signOut}/><main className="workspace"><header className="workspace-head"><div><p>{active==='overview'?'Tuesday, July 18':'Your money, in context'}</p><h1>{active==='overview'?<>Good morning, {firstName} <span>*</span></>:active[0].toUpperCase()+active.slice(1)}</h1></div><div className="head-actions"><button className="icon-btn" onClick={()=>{if('Notification' in window) void Notification.requestPermission()}}><Bell size={18}/><i/></button><div className="avatar">{firstName.slice(0,2).toUpperCase()}</div></div></header>{loading?<div className="dashboard-skeleton"><i/><i/><i/></div>:view}</main>{(newModal||modal)&&<SubscriptionModal subscription={modal} onClose={()=>{setModal(undefined);setNewModal(false)}} onSave={save}/>}</div>}
function Overview({total,items,onSee}:{total:number;items:Subscription[];onSee:()=>void}){const next=items.filter(x=>x.status!=='cancelled').slice(0,3);return <div className="overview"><section className="leak-hero"><div><span className="eyebrow"><TrendingDown size={14}/> Your money leak meter</span><h2>You could reclaim<br/><em>{money(total*.43)}</em> every month.</h2><p>That is {money(total*.43*12)} a year from subscriptions that have not earned their place lately.</p><button className="button" onClick={onSee}>Review subscriptions <ChevronRight size={16}/></button></div><div className="leak-ring"><strong>{Math.round(total?total*.43/total*100:0)}<small>%</small></strong><span>potential savings</span></div></section><div className="metric-grid"><Metric icon={<WalletCards/>} label="Monthly spending" value={money(total)} note={`Across ${items.length} subscriptions`}/><Metric icon={<CircleDollarSign/>} label="Yearly commitment" value={money(total*12)} note="If nothing changes"/><Metric icon={<Sparkles/>} label="Health score" value="72" note="Good, with room to breathe" good/><Metric icon={<CalendarClock/>} label="Next renewal" value="2 days" note={items[0]?.name||'Netflix'}/></div><section className="two-col"><div className="panel renewals"><div className="panel-head"><div><p className="section-kicker">Next up</p><h3>Upcoming renewals</h3></div><button onClick={onSee}>View all <ChevronRight size={15}/></button></div>{next.map((s,i)=><div className="renewal" key={s.id}><div className={'subscription-logo l'+i}>{s.name.slice(0,1)}</div><div><b>{s.name}</b><span>{new Date(s.renewal_date).toLocaleDateString('en-US',{month:'short',day:'numeric'})} - {s.category}</span></div><strong>{money(s.cost)}<small>/{s.billing_cycle==='monthly'?'mo':'yr'}</small></strong></div>)}</div><div className="panel ai-card"><div className="ai-orb"><Sparkles size={20}/></div><p className="section-kicker">Offtrack insight</p><h3>Your biggest expense is Adobe.</h3><p>At $720/year, it accounts for nearly half your creative-tool spend. If you have not used it this month, it is worth a pause.</p><button onClick={onSee}>Explore options <ChevronRight size={15}/></button></div></section></div>}
function Metric({icon,label,value,note,good}:{icon:ReactNode;label:string;value:string;note:string;good?:boolean}){return <article className="metric"><span className={good?'green':''}>{icon}</span><p>{label}</p><strong>{value}</strong><small>{note}</small></article>}
function Subscriptions({items,query,setQuery,onEdit,onDelete}:{items:Subscription[];query:string;setQuery:(q:string)=>void;onEdit:(x:Subscription)=>void;onDelete:(id:string)=>void}){return <div className="subscriptions-page"><div className="list-toolbar"><div className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search subscriptions"/></div><button className="filter">Active <ChevronRight size={15}/></button></div><div className="list-panel"><div className="list-label"><span>SUBSCRIPTION</span><span>RENEWS</span><span>MONTHLY COST</span><span/></div>{items.map((s,i)=><div className="sub-row" key={s.id}><div><div className={'subscription-logo l'+i}>{s.name.slice(0,1)}</div><span><b>{s.name}</b><small>{s.category} - <i className={s.status}/>{s.status}</small></span></div><time>{new Date(s.renewal_date).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</time><strong>{money(monthly(s))}<small>/mo</small></strong><div className="row-actions"><button onClick={()=>onEdit(s)}><MoreHorizontal size={18}/></button><button onClick={()=>onDelete(s.id)} title="Delete subscription"><X size={16}/></button></div></div>)}{!items.length&&<p className="empty-list">Nothing matches that search.</p>}</div></div>}
function Calendar({items}:{items:Subscription[]}){return <div className="calendar-panel"><FullCalendar plugins={[dayGridPlugin]} initialView="dayGridMonth" height="auto" events={items.map(x=>({title:`${x.name} - ${money(x.cost)}`,date:x.trial_end_date||x.renewal_date,color:x.status==='trial'?'#f59e0b':'#7c3aed'}))}/></div>}
function Analytics({items}:{items:Subscription[]}){const category=Object.entries(items.reduce<Record<string,number>>((a,x)=>{a[x.category]=(a[x.category]||0)+monthly(x);return a},{})).map(([name,value])=>({name,value}));const trend=['Feb','Mar','Apr','May','Jun','Jul'].map((name,i)=>({name,spend:Math.max(40,items.reduce((a,x)=>a+monthly(x),0)-i*7)}));const colors=['#8b5cf6','#06b6d4','#f59e0b','#22c55e','#ec4899'];return <div className="analytics"><section className="analytics-lead"><p className="section-kicker">Spending signal</p><h2>See the pattern.<br/><em>Change the ending.</em></h2><p>Your current active stack costs {money(items.reduce((a,x)=>a+monthly(x),0)*12)} per year.</p></section><div className="chart-grid"><article className="chart-card wide"><h3>Monthly spend trend</h3><ResponsiveContainer width="100%" height={220}><BarChart data={trend}><XAxis dataKey="name" axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="spend" radius={[7,7,0,0]} fill="#8b5cf6"/></BarChart></ResponsiveContainer></article><article className="chart-card"><h3>Category mix</h3><ResponsiveContainer width="100%" height={220}><PieChart><Pie data={category} dataKey="value" nameKey="name" innerRadius={50} outerRadius={80}>{category.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div className="legend">{category.map((x,i)=><span key={x.name}><i style={{background:colors[i%colors.length]}}/>{x.name}</span>)}</div></article></div></div>}
function EmptyPanel({active}:{active:string}){return <div className="empty-panel"><Sparkles/><h2>{active==='profile'?'Your profile belongs to you.':'Fine-tune your calm.'}</h2><p>Profile and notification preferences are stored privately with your account.</p></div>}
export function LiveDashboard(){const {session}=useAuth();const [revision,setRevision]=useState(0);useEffect(()=>{const client=supabase;if(!client||!session?.user.id)return;const channel=client.channel(`subscriptions:${session.user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'Subscriptions',filter:`user_id=eq.${session.user.id}`},()=>setRevision(x=>x+1)).subscribe();return()=>{void client.removeChannel(channel)}},[session?.user.id]);return <Dashboard key={revision}/>}
