import { motion } from 'framer-motion'
import { ArrowRight, Check, ChevronDown, Play, ShieldCheck, Sparkles, Star } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Logo } from '../components/Logo'

const cards = [{ name: 'Netflix', amount: '$22.99', icon: 'N', tone: 'red' }, { name: 'Notion', amount: '$10.00', icon: 'N', tone: 'gray' }, { name: 'Spotify', amount: '$11.99', icon: '●', tone: 'green' }]
const faqs = [['Does it connect to my bank?', 'No. You stay in control. Add subscriptions manually, then we turn the list into a clear plan.'], ['Is my information secure?', 'Yes. Authentication and session management are powered by Supabase with secure, persistent sessions.'], ['Can I cancel from the app?', 'We surface clear, official cancellation paths so you can make the decision without the scavenger hunt.']]
export function Landing() {
 return <main><div className="aurora a1"/><div className="aurora a2"/><div className="grain"/>
  <nav><Logo/><div className="nav-links"><a href="#how">How it works</a><a href="#stories">Stories</a><a href="#faq">FAQ</a></div><div className="nav-actions"><Link to="/login" className="text-link">Sign in</Link><Link to="/signup" className="button small">Start for free <ArrowRight size={14}/></Link></div></nav>
  <section className="hero"><motion.div initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="eyebrow"><Sparkles size={14}/> Your money, back in focus</motion.div><motion.h1 initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{delay:.1}}>Stop paying for<br/><em>subscriptions</em> you forgot.</motion.h1><motion.p initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{delay:.2}}>Meet the quiet recurring costs hiding in plain sight. Offtrack gives every charge a reason to stay — or a reason to go.</motion.p><motion.div initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{delay:.3}} className="hero-actions"><Link to="/signup" className="button">Find my money leaks <ArrowRight size={17}/></Link><a href="#how" className="play"><span><Play size={13} fill="currentColor"/></span> See how it works</a></motion.div><div className="trust"><ShieldCheck size={15}/> No bank connection required <b>·</b> Private by design</div>
  <motion.div initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{delay:.35,duration:.7}} className="orbit"><div className="meter"><span>MONTHLY LEAK</span><strong>$127<span>.48</span></strong><p><i/> $54.99 recoverable this month</p></div>{cards.map((c,i)=><motion.div key={c.name} animate={{y:[0,i%2?8:-7,0]}} transition={{repeat:Infinity,duration:4+i, ease:'easeInOut'}} className={'sub-card card-'+i}><div className={'brand '+c.tone}>{c.icon}</div><div><b>{c.name}</b><small>Renews in {i+2} days</small></div><strong>{c.amount}</strong></motion.div>)}</motion.div></section>
  <section id="how" className="section steps"><div className="section-kicker">A calmer way to spend</div><h2>Every recurring charge<br/>gets a <em>moment of truth.</em></h2><div className="step-grid">{[['01','Gather','Bring the subscriptions you can remember.'],['02','Understand','See what they cost you over time.'],['03','Decide','Keep what earns its place. Release the rest.']].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section id="stories" className="quote-section"><div className="quote-mark">“</div><blockquote>It wasn’t one huge bill. It was a dozen little yeses I never revisited.</blockquote><div className="person"><div>MK</div><span><b>Maya K.</b><small>Found $438/year in forgotten spend</small></span><div className="stars">{[1,2,3,4,5].map(x=><Star key={x} size={13} fill="currentColor"/>)}</div></div></section>
  <section id="faq" className="section faq"><div><div className="section-kicker">The small print, made human</div><h2>Questions,<br/><em>answered.</em></h2></div><div>{faqs.map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={18}/></summary><p>{a}</p></details>)}</div></section>
  <section className="closing"><Sparkles size={19}/><h2>Your next saved dollar<br/>is waiting.</h2><Link to="/signup" className="button">Start finding it <ArrowRight size={17}/></Link></section>
  <footer><Logo/><span>© 2026 Offtrack. Made for intentional spending.</span><div><a href="#">Privacy</a><a href="#">Terms</a></div></footer>
 </main>
}
